name: slack_webhook
description: Create and send messages using Slack Incoming Webhooks. Complete support for Block(s).
version: 1.0.1
repository: https://github.com/devanced/dart-slack3

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  http: ^1.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
